resilience4j:
  circuitbreaker:
    instances:
      departmentService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        record-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException


logging:
  level:
    org.springframework.web: DEBUG
    io.github.resilience4j: DEBUG
